services:
  api-gateway:
    image: samarkinivan/api-gateway:latest
    container_name: api-gateway
    restart: on-failure
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file: .env
    ports:
      - '8080:8080'
